SET FOREIGN_KEY_CHECKS=0;

DROP TABLE `users_posts`;
ALTER TABLE `posts` ADD `user_id` MEDIUMINT NOT NULL AFTER `id`,
ADD CONSTRAINT FOREIGN KEY(`user_id`) REFERENCES `users`(`id`);

SET FOREIGN_KEY_CHECKS=1;